{
  "modified": "2024-10-24T01:01:59Z",
  "published": "2024-06-25T13:38:20Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5500",
  "aliases": [
    "SNYK-PYTHON-PIPCOLOUREXTENSION-5932333"
  ],
  "summary": "Malicious code in pipcolourextension (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pipcolourextension",
        "purl": "pkg:pypi/pipcolourextension"
      },
      "versions": [
        "1.1.0",
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PIPCOLOUREXTENSION-5932333"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "dc030b6836017a778733c765345180469657992d138d7fdefa118ef215949fbd",
        "import_time": "2024-06-28T02:49:41.708740579Z",
        "id": "RLMA-2024-04282",
        "modified_time": "2024-06-25T13:38:20Z",
        "versions": [
          "1.1.0",
          "1.0.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "2fcfa0b72b55c7cb72648b299866c50a9e9a8fe9456f0a5417a0bc738b31f5ae",
        "import_time": "2024-10-24T00:59:36.8584549Z",
        "id": "RLUA-2024-08710",
        "modified_time": "2024-10-16T14:45:41Z"
      }
    ]
  }
}
