{
  "modified": "2024-10-24T01:01:59Z",
  "published": "2024-06-25T13:43:24Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-6113",
  "aliases": [
    "SNYK-PYTHON-TESTFIWLDSD21233S-5885055"
  ],
  "summary": "Malicious code in testfiwldsd21233s (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "testfiwldsd21233s",
        "purl": "pkg:pypi/testfiwldsd21233s"
      },
      "versions": [
        "0.1"
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/DataDog/malicious-software-packages-dataset"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-TESTFIWLDSD21233S-5885055"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "fdf6316a1ef1072411a72a8fa3b07e529d58ce284018411f20f81dda8af5443d",
        "import_time": "2024-06-28T02:50:57.75110696Z",
        "id": "RLMA-2024-04917",
        "modified_time": "2024-06-25T13:43:24Z",
        "versions": [
          "0.1"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "0afd0b2aa009d5ddcaf8afdea45036df0fb13e0ce87f62bade064ce008aa2ff2",
        "import_time": "2024-10-24T01:00:18.627046564Z",
        "id": "RLUA-2024-09386",
        "modified_time": "2024-10-16T14:52:34Z"
      }
    ]
  }
}
