{
  "modified": "2024-10-16T14:40:49Z",
  "published": "2024-10-16T14:40:49Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-10014",
  "summary": "Malicious code in etheurm (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "etheurm",
        "purl": "pkg:pypi/etheurm"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-08241",
        "import_time": "2024-10-24T00:56:58.610338792Z",
        "modified_time": "2024-10-16T14:40:49Z",
        "sha256": "d92229be06dbf145daa5c58a94abc3922139b37c1b75622ebc3102bd5a2533cd",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
