{
  "modified": "2025-04-22T06:46:01Z",
  "published": "2025-04-22T06:46:01Z",
  "schema_version": "1.5.0",
  "id": "MAL-2025-3278",
  "summary": "Malicious code in subdomainer (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n\n## Source: ossf-package-analysis (7a632d46c9cda2dc51b4f8dabb8860c8bed1f5c0250dc785770b881f6b88c4d6)\nThe OpenSSF Package Analysis project identified 'subdomainer' @ 1.0.0 (pypi) as malicious.\n\nIt is considered malicious because:\n\n- The package communicates with a domain associated with malicious activity.\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "subdomainer"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "OpenSSF: Package Analysis",
      "type": "FINDER",
      "contact": [
        "https://github.com/ossf/package-analysis",
        "https://openssf.slack.com/channels/package_analysis"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "import_time": "2025-04-22T07:06:27.427896318Z",
        "modified_time": "2025-04-22T06:46:01Z",
        "sha256": "7a632d46c9cda2dc51b4f8dabb8860c8bed1f5c0250dc785770b881f6b88c4d6",
        "source": "ossf-package-analysis",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
