{
  "modified": "2025-04-23T16:06:32Z",
  "published": "2025-04-23T16:06:32Z",
  "schema_version": "1.5.0",
  "id": "MAL-2025-3456",
  "summary": "Malicious code in pyapimove (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pyapimove",
        "purl": "pkg:pypi/pyapimove"
      },
      "versions": [
        "1.0.0",
        "1.0.1"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2025-02519",
        "import_time": "2025-04-25T09:36:47.239581652Z",
        "modified_time": "2025-04-23T16:06:32Z",
        "sha256": "43b42c11cba16fbfa9033392125edd684eea50a8eccac9903ff2db5f6435b903",
        "source": "reversing-labs",
        "versions": [
          "1.0.0",
          "1.0.1"
        ]
      }
    ]
  }
}
