{
  "modified": "2024-10-24T01:01:58Z",
  "published": "2024-06-25T13:33:45Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-4934",
  "aliases": [
    "SNYK-PYTHON-COLORAMU-6513694"
  ],
  "summary": "Malicious code in coloramu (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "coloramu",
        "purl": "pkg:pypi/coloramu"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-COLORAMU-6513694"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "e341c8a6890795cc05b6b90ee634b4edf7b89683acd97d34e4a38afe436da240",
        "import_time": "2024-06-28T02:48:35.182676724Z",
        "id": "RLMA-2024-03714",
        "modified_time": "2024-06-25T13:33:45Z",
        "versions": [
          "1.0.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "896aa98319c1ee4750c839a49038b35c670d3d13eb2a79fa122b357f04e02431",
        "import_time": "2024-10-24T00:58:57.662522087Z",
        "id": "RLUA-2024-08005",
        "modified_time": "2024-10-16T14:38:19Z"
      }
    ]
  }
}
