{
  "modified": "2024-10-24T01:01:58Z",
  "published": "2024-06-25T13:35:03Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5095",
  "aliases": [
    "SNYK-PYTHON-DPYBOT-5295932"
  ],
  "summary": "Malicious code in dpy-bot (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "dpy-bot",
        "purl": "pkg:pypi/dpy-bot"
      },
      "versions": [
        "1.0"
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/DataDog/malicious-software-packages-dataset"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-DPYBOT-5295932"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "3ec940cd3e1c69f7235caab8f4ed441362e3bc15b1384d5ba25417be42b4c2b2",
        "import_time": "2024-06-28T02:48:53.392871149Z",
        "id": "RLMA-2024-03875",
        "modified_time": "2024-06-25T13:35:03Z",
        "versions": [
          "1.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "8b630b491e988cadb3c5535d7e4f65dbb763667bdaaccaab9d24ce4784100668",
        "import_time": "2024-10-24T00:59:09.238831446Z",
        "id": "RLUA-2024-08172",
        "modified_time": "2024-10-16T14:40:05Z"
      }
    ]
  }
}
