{
  "modified": "2025-09-26T11:06:46Z",
  "published": "2025-03-28T13:06:22Z",
  "schema_version": "1.5.0",
  "id": "MAL-2025-3006",
  "aliases": [
    "SNYK-PYTHON-TCLOUDPYTHONTEST-12201353"
  ],
  "summary": "Malicious code in tcloud-python-test (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "tcloud-python-test",
        "purl": "pkg:pypi/tcloud-python-test"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://x.com/ReversingLabs/status/1900198602242204003"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-TCLOUDPYTHONTEST-12201353"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "b4be4b1ed6050855e2f9c6b1bfa0a9cd4c34a16211339ae604603d0e6aed6ba1",
        "import_time": "2025-03-31T07:07:06.980236897Z",
        "id": "RLMA-2025-02005",
        "modified_time": "2025-03-28T13:06:22Z",
        "versions": [
          "1.0.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "5852c723e0b065d1baa10c7bf39fcc721dc7670afb0d2b0e6a2b3cdfb2ec75ca",
        "import_time": "2025-09-26T11:06:10.935474543Z",
        "id": "RLUA-2025-04811",
        "modified_time": "2025-09-26T09:14:39Z"
      }
    ]
  }
}
