{
  "modified": "2025-05-22T12:33:59Z",
  "published": "2025-05-22T12:33:59Z",
  "schema_version": "1.5.0",
  "id": "MAL-2025-4268",
  "summary": "Malicious code in web3-validators (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "web3-validators",
        "purl": "pkg:pypi/web3-validators"
      },
      "versions": [
        "2.0.0",
        "2.1.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2025-02626",
        "import_time": "2025-05-22T14:06:40.117892965Z",
        "modified_time": "2025-05-22T12:33:59Z",
        "sha256": "72f1ca6acacbcefeb4f4fe7aaacd61d4f12d95f4438db09c910ea479740fce20",
        "source": "reversing-labs",
        "versions": [
          "2.0.0",
          "2.1.0"
        ]
      }
    ]
  }
}
