{
  "modified": "2024-10-24T01:02:00Z",
  "published": "2024-06-25T13:44:32Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-6261",
  "aliases": [
    "SNYK-PYTHON-ZPROXY2-5295975"
  ],
  "summary": "Malicious code in zproxy2 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "zproxy2",
        "purl": "pkg:pypi/zproxy2"
      },
      "versions": [
        "1.0"
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/DataDog/malicious-software-packages-dataset"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-ZPROXY2-5295975"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "75b887e0b097e6f5420e8685cc892ff85bd26dfbf375ed2af7ea571d1ffeb880",
        "import_time": "2024-06-28T02:51:15.579285949Z",
        "id": "RLMA-2024-05065",
        "modified_time": "2024-06-25T13:44:32Z",
        "versions": [
          "1.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "d6430a6253d8f616b9c184ac2e3d2a445c8efdb02fa07a59ba4282d4269fa244",
        "import_time": "2024-10-24T01:00:29.01868689Z",
        "id": "RLUA-2024-09584",
        "modified_time": "2024-10-16T14:54:37Z"
      }
    ]
  }
}
