{
  "modified": "2024-10-24T01:01:59Z",
  "published": "2024-06-25T13:41:01Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5818",
  "aliases": [
    "SNYK-PYTHON-PYTHONFONTSV2-5932314"
  ],
  "summary": "Malicious code in pythonfontsv2 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pythonfontsv2",
        "purl": "pkg:pypi/pythonfontsv2"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYTHONFONTSV2-5932314"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "6e0144521e8609e5e14f23d5a947817bf2566ef1c97a81c3f1b66e60e1654107",
        "import_time": "2024-06-28T02:50:21.270030718Z",
        "id": "RLMA-2024-04616",
        "modified_time": "2024-06-25T13:41:01Z",
        "versions": [
          "1.0.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "5ba32060d6c5c92fcb14c8750ee8a56ce3e2a38636850b6b9b89bc03edf7250d",
        "import_time": "2024-10-24T00:59:58.441238508Z",
        "id": "RLUA-2024-09057",
        "modified_time": "2024-10-16T14:49:13Z"
      }
    ]
  }
}
