{
  "modified": "2024-10-24T01:01:59Z",
  "published": "2024-06-25T13:43:24Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-6114",
  "summary": "Malicious code in testing1232 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "testing1232",
        "purl": "pkg:pypi/testing1232"
      },
      "versions": [
        "0.0.1"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "65d4597527d26e54bde17ceef57e210a8d4fb84fff908fe03a81310384658b74",
        "import_time": "2024-06-28T02:50:57.854728159Z",
        "id": "RLMA-2024-04918",
        "modified_time": "2024-06-25T13:43:24Z",
        "versions": [
          "0.0.1"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "a20efd02e46e96c26374f4ead55f4cb6783d1d29af3909a158b6954d0e984c4b",
        "import_time": "2024-10-24T01:00:18.688608433Z",
        "id": "RLUA-2024-09387",
        "modified_time": "2024-10-16T14:52:35Z"
      }
    ]
  }
}
