{
  "modified": "2024-10-24T01:01:59Z",
  "published": "2024-06-25T13:43:10Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-6084",
  "aliases": [
    "SNYK-PYTHON-SYSSQLITE3LIBERYV1-5932110"
  ],
  "summary": "Malicious code in syssqlite3liberyv1 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "syssqlite3liberyv1",
        "purl": "pkg:pypi/syssqlite3liberyv1"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-SYSSQLITE3LIBERYV1-5932110"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "22f61b67cc223495b4835e9bd3e3587868a000897554a54e6036d2174bc6c4ab",
        "import_time": "2024-06-28T02:50:54.31242028Z",
        "id": "RLMA-2024-04887",
        "modified_time": "2024-06-25T13:43:10Z",
        "versions": [
          "1.0.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "079ab4e91af23b3f1ba68ffd1c0afc41471e927835bb42dba30f2f1427bae7ea",
        "import_time": "2024-10-24T01:00:16.605526298Z",
        "id": "RLUA-2024-09355",
        "modified_time": "2024-10-16T14:52:16Z"
      }
    ]
  }
}
